
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8779

#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: 127.0.0.1
    # 实例是否允许使用IP
    preferIpAddress: false

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl.defaultZone: http://${eureka.instance.hostname}:8777/eureka/

#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 应用程序名称
  application:
    name: platform-cloud-gateway

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default

  # 分布式配置中心
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: platform-cloud-config


    # 网关路由配置
    gateway:
      defaultFilters:
      - PreserveHostHeader
      routes:
      # 平台服务  http请求为lb://     ws请求为lb:ws://表示将请求负载到哪一个服务上
      - id: platform
        uri: lb://platform-cloud-wallet
        predicates:
        - Path=/platform/**
        #StripPrefix= 1表示把访问路径中的/platform去掉  天坑
        filters:
        - StripPrefix= 1
      # 后台服务
      - id: sign
        uri: lb://platform-cloud-sign
        predicates:
        - Path=/sign/**
        filters:
        - StripPrefix= 1
      # 共有服务
      - id: common
        uri: lb://bigsong-common
        predicates:
        - Path=/common/**
        filters:
        - StripPrefix= 1


# 日志配置
logging:
  config: classpath:config/logback-spring.xml
