package com.jrmf.domain;

import lombok.Data;

@Data
public class TaxCode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.id
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level1
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level2
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level3
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level4
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level5
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level6
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level7
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level8
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level9
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level10
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String level10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.code
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.name
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.desc
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.remark
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tax_code.level_code
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    private String levelCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.id
     *
     * @return the value of tax_code.id
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.id
     *
     * @param id the value for tax_code.id
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level1
     *
     * @return the value of tax_code.level1
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel1() {
        return level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level1
     *
     * @param level1 the value for tax_code.level1
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel1(String level1) {
        this.level1 = level1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level2
     *
     * @return the value of tax_code.level2
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel2() {
        return level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level2
     *
     * @param level2 the value for tax_code.level2
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel2(String level2) {
        this.level2 = level2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level3
     *
     * @return the value of tax_code.level3
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel3() {
        return level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level3
     *
     * @param level3 the value for tax_code.level3
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel3(String level3) {
        this.level3 = level3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level4
     *
     * @return the value of tax_code.level4
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel4() {
        return level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level4
     *
     * @param level4 the value for tax_code.level4
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel4(String level4) {
        this.level4 = level4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level5
     *
     * @return the value of tax_code.level5
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel5() {
        return level5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level5
     *
     * @param level5 the value for tax_code.level5
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel5(String level5) {
        this.level5 = level5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level6
     *
     * @return the value of tax_code.level6
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel6() {
        return level6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level6
     *
     * @param level6 the value for tax_code.level6
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel6(String level6) {
        this.level6 = level6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level7
     *
     * @return the value of tax_code.level7
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel7() {
        return level7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level7
     *
     * @param level7 the value for tax_code.level7
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel7(String level7) {
        this.level7 = level7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level8
     *
     * @return the value of tax_code.level8
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel8() {
        return level8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level8
     *
     * @param level8 the value for tax_code.level8
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel8(String level8) {
        this.level8 = level8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level9
     *
     * @return the value of tax_code.level9
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel9() {
        return level9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level9
     *
     * @param level9 the value for tax_code.level9
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel9(String level9) {
        this.level9 = level9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level10
     *
     * @return the value of tax_code.level10
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevel10() {
        return level10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level10
     *
     * @param level10 the value for tax_code.level10
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevel10(String level10) {
        this.level10 = level10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.code
     *
     * @return the value of tax_code.code
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.code
     *
     * @param code the value for tax_code.code
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.name
     *
     * @return the value of tax_code.name
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.name
     *
     * @param name the value for tax_code.name
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.desc
     *
     * @return the value of tax_code.desc
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getDesc() {
        return desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.desc
     *
     * @param desc the value for tax_code.desc
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setDesc(String desc) {
        this.desc = desc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.remark
     *
     * @return the value of tax_code.remark
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.remark
     *
     * @param remark the value for tax_code.remark
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tax_code.level_code
     *
     * @return the value of tax_code.level_code
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public String getLevelCode() {
        return levelCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tax_code.level_code
     *
     * @param levelCode the value for tax_code.level_code
     *
     * @mbg.generated Mon Nov 16 18:05:53 CST 2020
     */
    public void setLevelCode(String levelCode) {
        this.levelCode = levelCode;
    }
}
