package com.jrmf.payment.mybankapi.common.exceptions;

public enum ReturnCode {

  INPUT_CHARSET_ERROR("INPUT_CHARSET_ERROR", "编码类型错误"),

  REQUIRED_FIELD_NOT_EXIST("REQUIRED_FIELD_NOT_EXIST", "必填字段未填写"),

  ILLEGAL_ACCESS_SWITCH_SYSTEM("ILLEGAL_ACCESS_SWITCH_SYSTEM", "商户不允许访问该类型的接口"),

  FIELD_LENGTH_EXCEEDS_LIMIT("FIELD_LENGTH_EXCEEDS_LIMIT", "字段长度超过限制"),

  FIELD_TYPE_ERROR("FIELD_TYPE_ERROR", "字段类型错误"),

  ILLEGAL_ARGUMENT("ILLEGAL_ARGUMENT", "参数校验未通过"),

  ILLEGAL_SIGN_TYPE("ILLEGAL_SIGN_TYPE", "签名类型不正确"),

  ILLEGAL_SIGN("ILLEGAL_SIGN", "验签未通过"),

  ILLEGAL_SERVICE("ILLEGAL_SERVICE", "服务接口不存在"),

  TRADE_DATA_MATCH_ERROR("TRADE_DATA_MATCH_ERROR", "交易信息有误"),

  ILLEGAL_AMOUNT_FORMAT("ILLEGAL_AMOUNT_FORMAT", "金额格式错误"),

  PREPAY_DATA_MATCH_ERROR("PREPAY_DATA_MATCH_ERROR", "订金下订信息有误"),

  SYSTEM_ERROR("SYSTEM_ERROR", "系统内部错误"),

  NOT_EXIST("F5001", "结果不存在"),

  PARAM_INVALID("F5002", "参数校验不通过"),

  UNKNOWN_REPORT_FORM_TYPE("F5101", "无法识别的表单类型"),

  CONFIG_ERROR("E0002", "配置错误"),

  ILLEGAL_ID_TYPE("ILLEGAL_ID_TYPE", "ID类型不支持"),

  USER_ACCOUNT_NOT_EXIST("USER_ACCOUNT_NOT_EXIST", "用户账号不存在"),

  MEMBER_ID_NOT_EXIST("MEMBER_ID_NOT_EXIST", "用户MemberId不存在"),

  PARTNER_ID_NOT_EXIST("PARTNER_ID_NOT_EXIST", "合作方Id不存在"),

  DUPLICATE_REQUEST_NO("DUPLICATE_REQUEST_NO", "重复的请求号"),

  ILLEGAL_OUTER_TRADE_NO("ILLEGAL_OUTER_TRADE_NO", "交易订单号不存在"),

  ILLEGAL_DATE_FORMAT("ILLEGAL_DATE_FORMAT", "日期格式错误"),

  ILLEGAL_MOBILE_FORMAT("ILLEGAL_MOBILE_FORMAT", "手机格式不合法"),

  PAY_METHOD_ERROR("PAY_METHOD_ERROR", "支付方式错误"),

  ILLEGAL_PAY_METHOD("ILLEGAL_PAY_METHOD", "支付方式未授权"),

  OPERATOR_ID_NOT_EXIST("OPERATOR_ID_NOT_EXIST", "操作员Id不存在"),

  TRADE_NO_MATCH_ERROR("TRADE_NO_MATCH_ERROR", "交易号信息有误"),

  ILLEGAL_ROYALTY_PARAMETERS("ILLEGAL_ROYALTY_PARAMETERS", "分润账号集错误"),

  MOBILE_NOT_EXIST("MOBILE_NOT_EXIST", "用户手机号不存在"),

  TRADE_AMOUNT_MATCH_ERROR("TRADE_AMOUNT_MATCH_ERROR", "交易内金额不匹配"),

  TRADE_PAY_MATCH_ERROR("TRADE_PAY_MATCH_ERROR", "交易与支付金额不匹配"),

  ILLEGAL_PREPAY_NO("ILLEGAL_PREPAY_NO", "订金下订单号错误"),

  ILLEGAL_REFUND_AMOUNT("ILLEGAL_REFUND_AMOUNT", "退款金额信息错误"),

  ILLEGAL_REQUEST("ILLEGAL_REQUEST", "风控未通过"),

  ILLEGAL_ENSURE_AMOUNT("ILLEGAL_ENSURE_AMOUNT", "担保金额信息错误"),

  ILLEGAL_TIME_INTERVAL("ILLEGAL_TIME_INTERVAL", "时间区间错误"),

  CREATE_PERSON_MEMBER_ERROR("CREATE_PERSON_MEMBER_ERROR", "交易中创建个人会员失败"),

  CREATE_ACCOUNT_ERROR("CREATE_ACCOUNT_ERROR", "交易中创建账户失败"),

  QUERY_MEMBER_ERROR("QUERY_MEMBER_ERROR", "查询会员信息失败"),

  ACCOUNT_TYPE_NOT_SUPPORTED("ACCOUNT_TYPE_NOT_SUPPORTED", "账户类型不支持"),

  TRADE_TYPE_NOT_SUPPORTED("TRADE_TYPE_NOT_SUPPORTED", "交易类型不支持"),

  ILLEGAL_FUND_TYPE("ILLEGAL_FUND_TYPE", "资金类型不支持"),

  TOTAL_AMOUNT_MATCH_ERROR("TOTAL_AMOUNT_MATCH_ERROR", "赔偿订金金额+交易分润金额必须等于原下订金额"),

  TRANSFER_TYPE_NOT_SUPPORTED("TRANSFER_TYPE_NOT_SUPPORTED", "转账类型不支持"),

  CARD_ATTRIBUTE_NOT_SUPPORTED("CARD_ATTRIBUTE_NOT_SUPPORTED", "卡属性只支持 B对公，C对私"),

  CARD_TYPE_NOT_SUPPORTED("CARD_TYPE_NOT_SUPPORTED", "卡类型不支持"),

  ACCOUNT_NAME_DECRYPT_ERROR("ACCOUNT_NAME_DECRYPT_ERROR", "银行卡账户名解密失败"),

  CARD_NO_DECRYPT_ERROR("CARD_NO_DECRYPT_ERROR", "银行卡号解密失败"),

  IS_WEB_ACCESS_NOT_SUPPORTED("IS_WEB_ACCESS_NOT_SUPPORTED", "是否是网站访问只支持Y是，N否"),

  CHECK_PAY_CHANNEL_FAIL("CHECK_PAY_CHANNEL_FAIL", "网银支付渠道校验失败"),

  ILLEGAL_ORDER_NO_FORMAT("ILLEGAL_ORDER_NO_FORMAT", "订单号格式错误"),

  MEMBER_OR_ACCOUNT_QUERY_FAIL("MEMBER_OR_ACCOUNT_QUERY_FAIL", "会员/账户查询异常"),

  SESSION_TIMEOUT("SESSION_TIMEOUT", "session超时"),

  EXTERFACE_INVOKE_CONTEXT_EXPIRED("EXTERFACE_INVOKE_CONTEXT_EXPIRED", "接口调用上下文过期"),

  CARD_INFO_MATCH_ERROR("CARD_INFO_MATCH_ERROR", "银行卡信息有误"),

  ILLEGAL_DECRYPT("ILLEGAL_DECRYPT", "解密失败"),

  IDENTITY_EXIST_ERROR("IDENTITY_EXIST_ERROR", "会员标识已经存在"),

  MEMBER_NOT_EXIST("MEMBER_NOT_EXIST", "会员不存在"),

  ACCOUNT_NOT_EXIST("ACCOUNT_NOT_EXIST", "账户不存在"),

  MOBILE_EXIST_ERROR("MOBILE_EXIST_ERROR", "修改手机号失败"),

  MEMBER_TYPE_ERROR("MEMBER_TYPE_ERROR", "会员类型错误"),

  BANK_CARD_NOT_EXIST("BANK_CARD_NOT_EXIST", "银行卡不存在"),

  ILLEGAL_BANK_CARD_NO("ILLEGAL_BANK_CARD_NO", "银行卡号不正确"),

  QCARD_CAN_NOT_UNBUNDLING("QCARD_CAN_NOT_UNBUNDLING", "快捷卡不能解绑"),

  NORMAL_CARD_IS_EXIST("NORMAL_CARD_IS_EXIST", "提现卡已存在"),

  NORMAL_CARD_IS_NOT_EXIST("NORMAL_CARD_IS_NOT_EXIST", "提现卡不存在"),

  DUPLICATE_VERIFY("DUPLICATE_VERIFY", "认证信息重复"),

  NOT_SUPPORT_DISCOUNT_PAY_METHOD("NOT_SUPPORT_DISCOUNT_PAY_METHOD", "不支持的折扣支付方式"),

  PARSE_DISCOUNT_PAY_METHOD_ERROR("PARSE_DISCOUNT_PAY_METHOD_ERROR", "解析折扣支付方式错误"),

  ORIGINAL_VOUCHER_INEXISTENCE("ORIGINAL_VOUCHER_INEXISTENCE", "原始凭证号不存在"),

  ACCESSCHANEL_NOT_SUPPORT("ACCESSCHANEL_NOT_SUPPORT", "不支持的终端类型"),

  TRADE_STATE_NOT_EXIST("TRADE_STATE_NOT_EXIST", "查询的交易状态不存在"),

  TRADE_OUTER_NO_SIZE_EXCEEDS_LIMIT("TRADE_OUTER_NO_SIZE_EXCEEDS_LIMIT", "外部订单号数超过限制"),

  SAVE_VOUCHER_FAIL("SAVE_VOUCHER_FAIL", "保存凭证号失败"),

  UPDATE_VOUCHER_FAIL("UPDATE_VOUCHER_FAIL", "更新凭证信息失败"),

  INVALID_FILE_NAME("INVALID_FILE_NAME", "无效的文件名");

  private final String code;

  private final String message;

  ReturnCode(String code, String message) {
    this.code = code;
    this.message = message;
  }

  public static ReturnCode getByCode(String code) {
    for (ReturnCode resultCode : ReturnCode.values()) {
      if (resultCode.getCode().equals(code)) {
        return resultCode;
      }
    }
    return null;
  }

  public String getCode() {
    return code;
  }

  public String getMessage() {
    return message;
  }

}
