package com.jrmf.persistence;


import com.jrmf.domain.AgreementTemplateMapping;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface AgreementTemplateMappingDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agreement_template_mapping
     *
     * @mbg.generated Wed Oct 21 17:48:13 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agreement_template_mapping
     *
     * @mbg.generated Wed Oct 21 17:48:13 CST 2020
     */
    int insert(AgreementTemplateMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agreement_template_mapping
     *
     * @mbg.generated Wed Oct 21 17:48:13 CST 2020
     */
    int insertSelective(AgreementTemplateMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agreement_template_mapping
     *
     * @mbg.generated Wed Oct 21 17:48:13 CST 2020
     */
    AgreementTemplateMapping selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agreement_template_mapping
     *
     * @mbg.generated Wed Oct 21 17:48:13 CST 2020
     */
    int updateByPrimaryKeySelective(AgreementTemplateMapping record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table agreement_template_mapping
     *
     * @mbg.generated Wed Oct 21 17:48:13 CST 2020
     */
    int updateByPrimaryKey(AgreementTemplateMapping record);

    String selectAgreementTemplateProvider(String agreementTemplateConsumer);
}
